import dotenv from "dotenv";

dotenv.config();

const {
  MYSQL_HOST,
  MYSQL_PORT,
  MYSQL_USERNAME,
  MYSQL_PASSWORD,
  MYSQL_DBNAME,
  REDIS_URL,
  PORT,
  JWT_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  CLOUDFLARE_R2_ACCESS_KEY_ID,
  CLOUDFLARE_R2_SECRET_ACCESS_KEY,
  CLOUDFLARE_R2_BUCKET_NAME,
  CLOUDFLARE_R2_CONNECTION_STRING,
  FRONTEND_URL,
  BETTER_AUTH_SECRET,
  BETTER_AUTH_URL,
} = process.env;

if (
  !MYSQL_HOST ||
  !MYSQL_PORT ||
  !MYSQL_USERNAME ||
  !MYSQL_PASSWORD ||
  !MYSQL_DBNAME ||
  !REDIS_URL ||
  !PORT ||
  !GOOGLE_CLIENT_ID ||
  !GOOGLE_CLIENT_SECRET ||
  !CLOUDFLARE_R2_ACCESS_KEY_ID ||
  !CLOUDFLARE_R2_SECRET_ACCESS_KEY ||
  !CLOUDFLARE_R2_BUCKET_NAME ||
  !CLOUDFLARE_R2_CONNECTION_STRING ||
  !FRONTEND_URL ||
  !BETTER_AUTH_SECRET ||
  !BETTER_AUTH_URL
) {
  throw new Error("Missing environment variables");
}

if (BETTER_AUTH_SECRET.length < 32)
  throw new Error("BETTER_AUTH_SECRET must contain at least 32 characters");
if (new URL(BETTER_AUTH_URL).pathname !== "/")
  throw new Error(
    "BETTER_AUTH_URL must be the public authentication origin without a path",
  );

export const config = {
  MYSQL: {
    HOST: MYSQL_HOST,
    PORT: Number(MYSQL_PORT),
    USERNAME: MYSQL_USERNAME,
    PASSWORD: MYSQL_PASSWORD,
    DBNAME: MYSQL_DBNAME,
  },
  REDIS_URL,
  PORT: Number(PORT),
  JWT_SECRET: JWT_SECRET ?? "",
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: GOOGLE_REDIRECT_URI ?? "",
  TRUST_PROXY: process.env.TRUST_PROXY ?? "",
  AUTH_PROXY_SECRET: process.env.AUTH_PROXY_SECRET,
  CLOUDFLARE_R2: {
    ACCESS_KEY_ID: CLOUDFLARE_R2_ACCESS_KEY_ID,
    SECRET_ACCESS_KEY: CLOUDFLARE_R2_SECRET_ACCESS_KEY,
    BUCKET_NAME: CLOUDFLARE_R2_BUCKET_NAME,
    CONNECTION_STRING: CLOUDFLARE_R2_CONNECTION_STRING,
  },
  FRONTEND_URL,
  BETTER_AUTH_SECRET,
  BETTER_AUTH_URL,
};
